services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      pull_policy: build
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    networks: 
      - bot-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks: 
      - bot-network


volumes:
  redis-data:

networks:
  bot-network:
    driver: bridge