name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, raspberry-ga]
    if: github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message, '[skipci]')

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Create .env file
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
  
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pull & Redeploy
        run: docker compose pull && docker compose up --build -d

      - name: Clean up
        run: rm -rf ./dist
