name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, raspberry-ga]
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy new build to app directory
        run: docker cp ./dist/. tgbot-link-to-video-app-1:/usr/src/app/dist

      - name: Restart PM2
        run: docker restart tgbot-link-to-video-app-1

      - name: Clean up
        run: rm -rf ./dist
