name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      USE_LOG_DEBUG:
        description: "Enable debug logs"
        required: true
        default: "true"
        type: choice
        options:
          - true
          - false
      FORCE_CACHE:
        description: "Force rebuild without cache"
        required: true
        default: "false"
        type: choice
        options:
          - true
          - false

jobs:
  build-and-deploy:
    runs-on: [self-hosted, raspberry-ga]
    if: github.ref == 'refs/heads/main' &&
      !contains(github.event.head_commit.message, '[skipci]')

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Create .env file
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=${{ secrets.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH }}" >> .env
          echo "LOG_DEBUG=${{ inputs.USE_LOG_DEBUG }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Pull latest images
        run: docker compose pull

      - name: Build and start containers
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.FORCE_CACHE }}" == "true" ]]; then
            docker compose build --no-cache
          else
            docker compose build
          fi
          docker compose up -d

      - name: Check containers status
        run: docker compose ps

      - name: Clean up
        run: rm -rf ./dist
